// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OTP.Repositories;

#nullable disable

namespace OTP.Repositories.Migrations
{
    [DbContext(typeof(OTPDbContext))]
    [Migration("20230812212927_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OTP.Domains.Models.CodedLists.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DocumentType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(8908),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(8912),
                            Name = "Proof Of Address"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(8914),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(8915),
                            Name = "Proof Of Id"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(8917),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(8918),
                            Name = "Proof Of DBS"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(8919),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(8920),
                            Name = "Proof Of Eligibility To Work"
                        });
                });

            modelBuilder.Entity("OTP.Domains.Models.CodedLists.EducationLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EducationLevel", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.CodedLists.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Gender", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9263),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9266),
                            Name = "Female"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9268),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9268),
                            Name = "Male"
                        });
                });

            modelBuilder.Entity("OTP.Domains.Models.CodedLists.TeachingPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TeachingPreference", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9466),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9467),
                            Name = "Online"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9469),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9470),
                            Name = "Student's Home"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9471),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9472),
                            Name = "Tutor's Home"
                        });
                });

            modelBuilder.Entity("OTP.Domains.Models.CodedLists.TimeRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TimeRange", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9569),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9570),
                            Name = "Before 12"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9571),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9572),
                            Name = "12 - 5 pm"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9573),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9574),
                            Name = "After 5 pm"
                        });
                });

            modelBuilder.Entity("OTP.Domains.Models.CodedLists.WeekDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("WeekDay", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9658),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9659),
                            Name = "Sunday"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9660),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9661),
                            Name = "Monday"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9662),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9663),
                            Name = "Tuesday"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9664),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9665),
                            Name = "Wednesday"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9666),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9667),
                            Name = "Thursday"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9668),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9669),
                            Name = "Friday"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9670),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 12, 21, 29, 27, 377, DateTimeKind.Utc).AddTicks(9671),
                            Name = "Saturday"
                        });
                });

            modelBuilder.Entity("OTP.Domains.Models.Common.UserImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserImage", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.ManyToMany.StudentSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubject", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.ManyToMany.TutorEducationLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorEducationLevel");
                });

            modelBuilder.Entity("OTP.Domains.Models.ManyToMany.TutorSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorSubject", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.ManyToMany.TutorTeachingPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeachingPreferenceId")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeachingPreferenceId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorTeachingPreference", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.Students.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LinkedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.Subjects.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.Tutors.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EnhancedDBSChecked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("RightToWorkVerified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Tutor", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.Tutors.TutorAvailibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TimeRangeId")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<int>("WeekDayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimeRangeId");

                    b.HasIndex("TutorId");

                    b.HasIndex("WeekDayId");

                    b.ToTable("TutorAvailibility", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.Tutors.TutorDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorDocument", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.ManyToMany.StudentSubject", b =>
                {
                    b.HasOne("OTP.Domains.Models.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OTP.Domains.Models.Subjects.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OTP.Domains.Models.ManyToMany.TutorEducationLevel", b =>
                {
                    b.HasOne("OTP.Domains.Models.CodedLists.EducationLevel", null)
                        .WithMany()
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OTP.Domains.Models.Tutors.Tutor", null)
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OTP.Domains.Models.ManyToMany.TutorSubject", b =>
                {
                    b.HasOne("OTP.Domains.Models.Subjects.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OTP.Domains.Models.Tutors.Tutor", null)
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OTP.Domains.Models.ManyToMany.TutorTeachingPreference", b =>
                {
                    b.HasOne("OTP.Domains.Models.CodedLists.TeachingPreference", null)
                        .WithMany()
                        .HasForeignKey("TeachingPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OTP.Domains.Models.Tutors.Tutor", null)
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OTP.Domains.Models.Students.Student", b =>
                {
                    b.HasOne("OTP.Domains.Models.CodedLists.EducationLevel", "EducationLevel")
                        .WithMany()
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationLevel");
                });

            modelBuilder.Entity("OTP.Domains.Models.Tutors.TutorAvailibility", b =>
                {
                    b.HasOne("OTP.Domains.Models.CodedLists.TimeRange", "TimeRange")
                        .WithMany()
                        .HasForeignKey("TimeRangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OTP.Domains.Models.Tutors.Tutor", "Tutor")
                        .WithMany("TutorAvailibilities")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OTP.Domains.Models.CodedLists.WeekDay", "WeekDay")
                        .WithMany()
                        .HasForeignKey("WeekDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeRange");

                    b.Navigation("Tutor");

                    b.Navigation("WeekDay");
                });

            modelBuilder.Entity("OTP.Domains.Models.Tutors.TutorDocument", b =>
                {
                    b.HasOne("OTP.Domains.Models.Tutors.Tutor", "Tutor")
                        .WithMany("TutorDocuments")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("OTP.Domains.Models.Tutors.Tutor", b =>
                {
                    b.Navigation("TutorAvailibilities");

                    b.Navigation("TutorDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
