// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OTP.Repositories;

#nullable disable

namespace OTP.Repositories.Migrations
{
    [DbContext(typeof(OTPDbContext))]
    partial class OTPDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OTP.Domains.Models.CodedLists.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DocumentType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(8962),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(8965),
                            Name = "Proof Of Address"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(8968),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(8969),
                            Name = "Proof Of Id"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(8971),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(8971),
                            Name = "Proof Of DBS"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(8973),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(8974),
                            Name = "Proof Of Eligibility To Work"
                        });
                });

            modelBuilder.Entity("OTP.Domains.Models.CodedLists.EducationLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EducationLevel", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.CodedLists.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Gender", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9316),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9317),
                            Name = "Female"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9318),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9319),
                            Name = "Male"
                        });
                });

            modelBuilder.Entity("OTP.Domains.Models.CodedLists.TeachingPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TeachingPreference", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9515),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9516),
                            Name = "Online"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9517),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9518),
                            Name = "Student's Home"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9519),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9520),
                            Name = "Tutor's Home"
                        });
                });

            modelBuilder.Entity("OTP.Domains.Models.CodedLists.TimeRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TimeRange", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9611),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9612),
                            Name = "Before 12"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9614),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9615),
                            Name = "12 - 5 pm"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9616),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9617),
                            Name = "After 5 pm"
                        });
                });

            modelBuilder.Entity("OTP.Domains.Models.CodedLists.WeekDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("WeekDay", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9705),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9706),
                            Name = "Sunday"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9708),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9708),
                            Name = "Monday"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9710),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9710),
                            Name = "Tuesday"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9712),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9712),
                            Name = "Wednesday"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9713),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9714),
                            Name = "Thursday"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9722),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9723),
                            Name = "Friday"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9724),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 13, 15, 2, 53, 472, DateTimeKind.Utc).AddTicks(9725),
                            Name = "Saturday"
                        });
                });

            modelBuilder.Entity("OTP.Domains.Models.Common.UserImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserImage", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.ManyToMany.StudentSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubject", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.ManyToMany.TutorEducationLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorEducationLevel", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.ManyToMany.TutorSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorSubject", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.ManyToMany.TutorTeachingPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeachingPreferenceId")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeachingPreferenceId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorTeachingPreference", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.Students.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Address2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Address3")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LinkedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("GenderId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.Subjects.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.Tutors.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Address2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Address3")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnhancedDBSChecked")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LinkedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("RightToWorkVerified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.ToTable("Tutor", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.Tutors.TutorAvailibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TimeRangeId")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<int>("WeekDayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimeRangeId");

                    b.HasIndex("TutorId");

                    b.HasIndex("WeekDayId");

                    b.ToTable("TutorAvailibility", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.Tutors.TutorDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorDocument", (string)null);
                });

            modelBuilder.Entity("OTP.Domains.Models.ManyToMany.StudentSubject", b =>
                {
                    b.HasOne("OTP.Domains.Models.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OTP.Domains.Models.Subjects.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OTP.Domains.Models.ManyToMany.TutorEducationLevel", b =>
                {
                    b.HasOne("OTP.Domains.Models.CodedLists.EducationLevel", null)
                        .WithMany()
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OTP.Domains.Models.Tutors.Tutor", null)
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OTP.Domains.Models.ManyToMany.TutorSubject", b =>
                {
                    b.HasOne("OTP.Domains.Models.Subjects.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OTP.Domains.Models.Tutors.Tutor", null)
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OTP.Domains.Models.ManyToMany.TutorTeachingPreference", b =>
                {
                    b.HasOne("OTP.Domains.Models.CodedLists.TeachingPreference", null)
                        .WithMany()
                        .HasForeignKey("TeachingPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OTP.Domains.Models.Tutors.Tutor", null)
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OTP.Domains.Models.Students.Student", b =>
                {
                    b.HasOne("OTP.Domains.Models.CodedLists.EducationLevel", "EducationLevel")
                        .WithMany()
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OTP.Domains.Models.CodedLists.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationLevel");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("OTP.Domains.Models.Tutors.Tutor", b =>
                {
                    b.HasOne("OTP.Domains.Models.CodedLists.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("OTP.Domains.Models.Tutors.TutorAvailibility", b =>
                {
                    b.HasOne("OTP.Domains.Models.CodedLists.TimeRange", "TimeRange")
                        .WithMany()
                        .HasForeignKey("TimeRangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OTP.Domains.Models.Tutors.Tutor", "Tutor")
                        .WithMany("TutorAvailibilities")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OTP.Domains.Models.CodedLists.WeekDay", "WeekDay")
                        .WithMany()
                        .HasForeignKey("WeekDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeRange");

                    b.Navigation("Tutor");

                    b.Navigation("WeekDay");
                });

            modelBuilder.Entity("OTP.Domains.Models.Tutors.TutorDocument", b =>
                {
                    b.HasOne("OTP.Domains.Models.Tutors.Tutor", "Tutor")
                        .WithMany("TutorDocuments")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("OTP.Domains.Models.Tutors.Tutor", b =>
                {
                    b.Navigation("TutorAvailibilities");

                    b.Navigation("TutorDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
